### ISSUE TITLE
If a reactor call `mempool.CheckTxAsync()`, it should be guaranteed to call `app.CheckTxAsync()` first.

### ISSUE THREAD

**Issue by jinsan-line** [line/ostracon#167]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by tnasu** [comment]
This is fixed by another solution(https://github.com/line/ostracon/pull/168).
