### ISSUE TITLE
BLS signature size is resized by the imported package

### ISSUE THREAD

**Issue by kokeshiM0chi** [line/ostracon#203]
## Summary
The size of the BLS sig and the size of the public key are not unique to the BLS signature. It is necessary to modify the processing corresponding to this.

## Problem Definition
When using this package `import "github.com/herumi/bls-go-binary/bls"`, we get bls signature size 48bytes and public key size 96bytes. But,  when using this package  `import "github.com/herumi/bls-eth-go-binary/bls"`, we get bls signature size 96bytes and public key size 48bytes.
Therefore, The process of determining whether or not it is a BLS signature with 96 bytes may become a bug in the future.

## Proposal
The type of signature is identified by checking the pubkey type of the signed validator.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by torao** [comment]
(accidentally closed by bot😱)

**Comment by kokeshiM0chi** [comment]
Since the BLS sig has been removed, this issue is also closed.
https://github.com/line/ostracon/pull/541
