### ISSUE TITLE
Change the message to the same to improve BLS signature verification performance

### ISSUE THREAD

**Issue by kokeshiM0chi** [line/ostracon#204]
## Summary
If the messages are the same, the messages are signed, and the messages are aggregated, the pairing map can be processed only once.

## Problem Definition
Verification of aggregated BLS signatures is easy when the messages are the same, as shown in the following formula. By simplifying the verification, the pairing mapping only needs to be performed once, and the computational complexity can be significantly reduced.

reference:
https://crypto.stanford.edu/~dabo/pubs/papers/BLSmultisig.html#BGLS03
<img width="951" alt="スクリーンショット 2021-03-24 11 15 57" src="https://user-images.githubusercontent.com/52264064/113230682-8363a600-92d4-11eb-92e7-226a142edaf4.png">

Therefore, it is necessary to change the message when signing to be the same.

## Proposal
The message used when signing is this structure. If all the `Timestamp` are the same, the message when signing will be the same.

```
type CanonicalVote struct {
	Type      SignedMsgType // type alias for byte
	Height    int64         `binary:"fixed64"`
	Round     int64         `binary:"fixed64"`
	BlockID   CanonicalBlockID
	Timestamp time.Time
	ChainID   string
}
```
Then we call this function to verify.
https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L843
____

## related issue
https://github.com/line/ostracon/issues/72

## see also by tendermint/tendermint:
https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-025-commit.md#decision
https://github.com/tendermint/tendermint/issues/2840#issuecomment-529122431

#### For Admin Use

- [x] Not duplicate issue
- [x] ~Appropriate labels applied~
- [x] ~Appropriate contributors tagged~
- [x] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Here is what tendermint/tendermint will use to get to BLS aggregation

**Comment by torao** [comment]
(accidentally closed by bot😱)

**Comment by kokeshiM0chi** [comment]
Since the BLS sig has been removed, this issue is also closed.
https://github.com/line/ostracon/pull/541
