### ISSUE TITLE
Contact: Hello

### ISSUE THREAD

**Issue by marbar3778** [line/ostracon#325]
Hey, 

I work Interchain, we are stewards of Cosmos-SDK, Tendermint and IBC. We would love to begin a chat with the LINE team to talk about various features that have been implemented and possibly will be implemented.

**Comment by egonspace** [comment]
Thank you for your interest. We are currently preparing a Slack channel for communication related to this repository. Please wait a few days.

**Comment by egonspace** [comment]
Due to the nature of large companies that value the LINE brand, there are issues such as security and monitoring of external communication channels, so the channel opening process is delayed. If there is an issue you want to hear a quick answer, you can write it down here.

**Comment by torao** [comment]
(accidentally closed by bot😱)
