### ISSUE TITLE
Change pubkey/privatekey type name from `ostracon` to `tendermint`

### ISSUE THREAD

**Issue by zemyblue** [line/ostracon#445]
## Summary

Change pubkey/privatekey type name from `ostracon` to `tendermint`

## Problem Definition

* secp256k1
https://github.com/line/ostracon/blob/adb46f33e9eda4115a0e85e6c30f4b6bfe04789f/crypto/secp256k1/secp256k1.go#L20-L21
* ed25519
https://github.com/line/ostracon/blob/adb46f33e9eda4115a0e85e6c30f4b6bfe04789f/crypto/ed25519/ed25519.go#L23-L24
* sr25519
https://github.com/line/ostracon/blob/adb46f33e9eda4115a0e85e6c30f4b6bfe04789f/crypto/sr25519/encoding.go#L11-L12

* etc

And maybe we need to change protobuf data or path.

## Proposal

We changed the key type name from #287 . But this change make to be difficult to use other cosmos-sdk compatibility tools for example cosmjs, keplr, pingpub and etc. But if we revert this type name, we can use it without any porting. 

So I proposal this change.

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by torao** [comment]
@zemyblue
I think it best to leave the `ostracon/` prefix to distinguish Ostracon-specific features since BLS keys (and Composite keys introduced in relation to BLS keys), among *etc.*, aren't compatible with the Cosmos SDK tools, to begin with. If they'll try to support the BLS and Ostracon implementation is adopted, then they would support `ostracon/` key names.

Can the modified PR be tested with cosmjs, keplr and other modules mentioned above to make sure the modification works well before merging it into `main` branch?

**Comment by zemyblue** [comment]
> @zemyblue I think it best to leave the `ostracon/` prefix to distinguish Ostracon-specific features since BLS keys (and Composite keys introduced in relation to BLS keys), among _etc._, aren't compatible with the Cosmos SDK tools, to begin with. If they'll try to support the BLS and Ostracon implementation is adopted, then they would support `ostracon/` key names.
> 
> Can the modified PR be tested with cosmjs, keplr and other modules mentioned above to make sure the modification works well before merging it into `main` branch?

Thank you. I also think so. We don't need to change the BLS's key name, composite keys also. 

And I am testing we can use `cosmjs` without modifying. When I tested in last two days, we can use `cosmjs` directly, but we need to add plugin options for the `Ostracon`'s `validator_info`. In the Ostracon's `validator_info`, `staking_power` is added that is difference with Tendermint. Tendermint's `validator_info` has `voting_power`. I need more testing.

**Comment by torao** [comment]
I see. So we can't confirm it works yet now, can it?
Then I’ll merge PR #445 into `main` branch after @kokeshiM0chi  approves it.

**Comment by zemyblue** [comment]
Yes, we can. I think #447 PR does not have any problem. And I already ready the PR to apply this change in `lbm-sdk`. So, I also think no problem it's good to merge after approving enough.
