### ISSUE TITLE
Consideration of Aggregate Signature by IASchnorr and Comparison with BLS

### ISSUE THREAD

**Issue by kokeshiM0chi** [line/ostracon#461]
## Summary
Consider introducing Schnorr signatures.
There are two main reasons.

1. ECDSA guarantees safety up to EUF-CMA. The Schnorr signature guarantees even stronger security, SUF-CMA.
2. Non-interactive aggregate signatures are supported by IASchnorr.

## Description
BLS is currently installed in Ostracon. It is necessary to perform performance comparison and compatibility check.
- Aggregate signature speed comparison
- Size comparison of aggregated signatures
- Compatibility with the ordering of messages to be signed

## Problem Definition
It targets the same problems as BLS and can achieve higher security.

## Proposal
Applies here. Schnorr signatures can also be applied to tx signatures.
https://github.com/line/ostracon/blob/v1.0.6/types/vote_set.go#L668

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by torao** [comment]
What are some candidates for comparable implementations used in some blockchain or equivalent production?

**Comment by kokeshiM0chi** [comment]
Here it is. https://github.com/ElementsProject/cross-input-aggregation

**Comment by kokeshiM0chi** [comment]
Since the BLS sig has been removed, this issue is also closed.
https://github.com/line/ostracon/pull/541
