### ISSUE TITLE
Remove VRF Proof from header for compatibility

### ISSUE THREAD

**Issue by ulbqb** [line/ostracon#554]
## Summary

I want to move `Block.Header.Proof` and `Block.Header.Round` from `Block.Header` to `Block.VRFParams`.

## Problem Definition

Like #543 #546, Ostracon should be as compatible as possible with IBC and Cosmos-SDK. Howerver the compatibility is low for light client, since Ostracon's header structure is different from Tendermint's one.

## Proposal

I would propose the following fixes:
```proto
message Block {
  Header                      header          = 1 [(gogoproto.nullable) = false];
  Data                        data            = 2 [(gogoproto.nullable) = false];
  ostracon.types.EvidenceList evidence        = 3 [(gogoproto.nullable) = false];
  Commit                      last_commit     = 4;
  VRFParams                   vrf_params      = 5; // new field!!
}

// new message!!
message VRFParams {
  int32 round = 1;
  bytes proof = 2;
}

// Header defines the structure of an Ostracon block header.
message Header {
  ...
  // *** Ostracon Extended Fields ***
  // Note that MaxHeaderSize must be modified when adding/removing fields.

  // vrf info
  // int32 round = 1000; // remove this field!!
  // bytes proof = 1001; // remove this field!!
}

```

`proof` and `round` are just moved from `header` to `vrf_params`. Keeping the header and commit structure the same as tendermint is compatible with tendermint for light client.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tnasu** [comment]
I agree with you. In addition, if you make the improvement, would you re-consider `Validation/Verification` with the below:
* BlockExectutor.ValidateBlock
* Block.Header.ValidateBasic
* LightBlock.ValidateBasic
* ValidatorSet.VerifyCommit
* ValidatorSet.VerifyCommitLight
* ValidatorSet.VerifyCommitLightTrusting
